from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / 'data'
CASES_DIR = DATA_DIR / 'cases'
ALERTS_DIR = DATA_DIR / 'alerts'
CANDIDATE_THRESHOLD = 0.45
HIGH_CONFIDENCE_THRESHOLD = 0.55
MATCH_WINDOW_SECONDS = 8.0
MIN_MATCHES_IN_WINDOW = 4
DETECTION_SIZE = (512, 512)
PROCESS_EVERY_N_FRAMES = 2
MAX_INFERENCE_WIDTH = 960
FPS_SMOOTHING = 20
