import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {MapPin,Users,WifiOff,Navigation,ShieldAlert,Route,Copy,UserPlus,Plus,RefreshCw,Phone,AlertTriangle,CheckCircle2,LocateFixed,Footprints} from 'lucide-react';
import {readUser} from '../auth';
import {RouteEngine,LocationTracker,formatDistance,formatEta,haversineMeters} from '../lib/routeEngine';
import {addDemoMembers,createGroup,flushQueue,getCurrentGroup,joinGroup,leaveGroup,queuedCount,setMemberStatus,subscribe,updateMyPosition} from '../lib/groupStore';

function RouteSvg({bundle,group,myPhone}){
  if(!bundle||!group)return null;
  const coords=bundle.coordinates, xs=coords.map(c=>c[0]),ys=coords.map(c=>c[1]); const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);
  const p=c=>[30+(c[0]-minX)/(maxX-minX)*740,350-(c[1]-minY)/(maxY-minY)*310];
  const step=Math.max(1,Math.floor(coords.length/300)); const pts=coords.filter((_,i)=>i%step===0).map(c=>p(c).join(',')).join(' ');
  return <svg viewBox="0 0 800 380" className="group-map-svg"><rect width="800" height="380" rx="18" fill="#f5efe5"/><polyline points={pts} fill="none" stroke="#d9c6b3" strokeWidth="7" strokeLinecap="round"/><polyline points={pts} fill="none" stroke="#e8630c" strokeWidth="3" strokeLinecap="round"/>{group.members.filter(m=>m.lat!=null).map(m=>{const [x,y]=p([m.lng,m.lat]);const mine=m.phone===myPhone;return <g key={m.phone} transform={`translate(${x} ${y})`}><circle r={mine?12:10} fill={m.status==='lost'?'#D64545':mine?'#8B1B1B':'#2563EB'} stroke="#fff" strokeWidth="4"/><text y="-16" textAnchor="middle" fontSize="10" fontWeight="800" fill="#2B2320">{m.name}</text></g>})}</svg>
}

export default function GroupLocation(){
 const user=readUser(); const [route,setRoute]=useState(null),[group,setGroup]=useState(getCurrentGroup()),[name,setName]=useState('My Wari Group'),[code,setCode]=useState(''),[tracked,setTracked]=useState(null),[error,setError]=useState(''),[online,setOnline]=useState(navigator.onLine),[queue,setQueue]=useState(queuedCount()); const tracker=useRef(null);
 const engine=useMemo(()=>route?new RouteEngine(route):null,[route]);
 useEffect(()=>{fetch('/data/route.json').then(r=>r.json()).then(setRoute);return subscribe(setGroup)},[]);
 useEffect(()=>{const on=()=>{setOnline(navigator.onLine);if(navigator.onLine){flushQueue();setQueue(0)}};window.addEventListener('online',on);window.addEventListener('offline',on);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',on)}},[]);
 useEffect(()=>{if(!engine||!group)return; const t=new LocationTracker(engine);tracker.current=t;try{t.start(pos=>{setTracked(pos);setGroup(updateMyPosition(user,pos,pos.route));setQueue(queuedCount())},e=>setError(e.message),()=>setError('Waiting for a more accurate GPS fix (≤50 m)…'))}catch(e){setError(e.message)}return()=>t.stop()},[engine,group?.code]);
 const mine=group?.members.find(m=>m.phone===user.phone); const stage=mine?.chainageKm!=null?engine?.stageAt(mine.chainageKm):null;
 const distances=(group?.members||[]).filter(m=>m.phone!==user.phone&&m.lat!=null&&mine?.lat!=null).map(m=>({...m,d:haversineMeters(mine,m)})).sort((a,b)=>a.d-b.d); const far=distances.filter(m=>m.d>500);
 const doCreate=()=>{try{setGroup(createGroup(name,user));setError('')}catch(e){setError(e.message)}}; const doJoin=()=>{try{setGroup(joinGroup(code.trim().toUpperCase(),user));setError('')}catch(e){setError(e.message)}};
 if(!group)return <div className="feature-screen"><div className="feature-topbar"><Link to="/portal">← Back to VariMitra</Link><b>Group Location Sharing</b></div><div className="group-setup"><div className="group-intro"><div className="big-icon"><Users/></div><h1>Stay together through the Wari</h1><p>Create a private yatra group or join one using a code. Once joined, every member gets route-aware live location, separation warnings and offline-safe route monitoring.</p></div><div className="setup-grid"><div className="setup-card"><Plus/><h2>Create Group</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Group name"/><button className="primary-btn" onClick={doCreate}>Create & start sharing</button></div><div className="setup-card"><UserPlus/><h2>Join Group</h2><input value={code} onChange={e=>setCode(e.target.value)} placeholder="VMXXXXX"/><button className="secondary-btn" onClick={doJoin}>Join with code</button></div></div>{error&&<p className="group-error">{error}</p>}</div>;
 return <div className="feature-screen"><div className="feature-topbar"><Link to="/portal">← Back to VariMitra</Link><b>Group Location Sharing</b><span className={online?'net-chip online':'net-chip'}>{online?'● Online':'● Offline mode'}</span></div><main className="group-page"><section className="group-head"><div><span className="eyebrow">ACTIVE YATRA GROUP</span><h1>{group.name}</h1><div className="group-code">Code <b>{group.code}</b><button onClick={()=>navigator.clipboard?.writeText(group.code)}><Copy size={14}/></button></div></div><div className="group-head-actions"><button className="secondary-btn" onClick={()=>{if(engine){addDemoMembers(engine);setGroup(getCurrentGroup())}}}>Add demo members</button><button className="secondary-btn" onClick={()=>{leaveGroup();setGroup(null)}}>Leave</button></div></section>
 <section className="group-stats"><div><LocateFixed/><b>{tracked?.fix.accuracy?`±${Math.round(tracked.fix.accuracy)} m`:'Waiting'}</b><span>GPS accuracy</span></div><div><Route/><b>{mine?.chainageKm!=null?formatDistance(mine.chainageKm):'—'}</b><span>Route covered</span></div><div><Footprints/><b>{mine?.chainageKm!=null?formatDistance(Math.max(0,route.totalKm-mine.chainageKm)):'—'}</b><span>To Pandharpur</span></div><div><Users/><b>{group.members.length}</b><span>Group members</span></div><div><WifiOff/><b>{queue}</b><span>Offline updates queued</span></div></section>
 {!online&&<div className="offline-callout"><WifiOff/><div><b>Offline mode active</b><span>Your cached Wari route, chainage, stage and group’s last synced positions still work. Your own new fixes are queued and will sync when connectivity returns.</span></div></div>}
 <div className="group-grid"><section className="panel"><div className="panel-title"><h2><Navigation size={17}/> Live group map</h2><span>Route-aware · cached offline</span></div><RouteSvg bundle={route} group={group} myPhone={user.phone}/><div className="route-summary"><b>{stage?`${stage.fromPlace} → ${stage.toPlace}`:'Finding current stage…'}</b><span>{tracked?.route&&!tracked.route.onRoute?`Off route by ${formatDistance(tracked.route.offsetM/1000)} — rejoin highlighted Wari corridor`:'On the Wari route'}</span></div></section>
 <section className="panel"><div className="panel-title"><h2><Users size={17}/> Members</h2><span>{far.length?`${far.length} separated`:'Everyone nearby'}</span></div><div className="member-list">{group.members.map(m=>{const d=m.phone===user.phone?0:(mine?.lat&&m.lat?haversineMeters(mine,m):null);return <div className={'member-row '+(m.status==='lost'?'member-lost':'')} key={m.phone}><div className="avatar">{m.name.slice(0,1).toUpperCase()}</div><div className="member-main"><b>{m.name}{m.phone===user.phone?' · You':''}</b><span>{m.lastSeen?`Updated ${new Date(m.lastSeen).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:'No location yet'} · {m.offline?'offline':'online'}</span><small>{m.chainageKm!=null?`${formatDistance(m.chainageKm)} along route`:''}</small></div><div className="member-actions">{d!=null&&m.phone!==user.phone&&<strong className={d>500?'warn':''}>{d<1000?`${Math.round(d)} m`:`${(d/1000).toFixed(1)} km`}</strong>}{m.phone!==user.phone&&<button title={m.status==='lost'?'Mark safe':'Mark as lost'} onClick={()=>{setMemberStatus(m.phone,m.status==='lost'?'safe':'lost');setGroup(getCurrentGroup())}}>{m.status==='lost'?<CheckCircle2 size={17}/>:<ShieldAlert size={17}/>}</button>}<a href={`tel:${m.phone}`}><Phone size={16}/></a></div></div>})}</div></section></div>
 {far.length>0&&<section className="separation-alert"><AlertTriangle/><div><b>Group separation detected</b><span>{far.map(x=>x.name).join(', ')} {far.length===1?'is':'are'} more than 500 m from you. Use their route position above to rejoin.</span></div></section>}
 <section className="panel"><div className="panel-title"><h2><Route size={17}/> Route monitor & offline prediction</h2><span>Fixed Wari polyline · no routing API</span></div><div className="route-monitor-grid"><div><span>Current stage</span><b>{stage?`${stage.dayNumber}. ${stage.fromPlace} → ${stage.toPlace}`:'—'}</b></div><div><span>Remaining route</span><b>{mine?.chainageKm!=null?formatDistance(route.totalKm-mine.chainageKm):'—'}</b></div><div><span>Walking ETA @ 3 km/h</span><b>{mine?.chainageKm!=null?formatEta(route.totalKm-mine.chainageKm):'—'}</b></div><div><span>GPS samples accepted</span><b>{tracked?.sampleCount||0}</b></div></div><p className="honesty-note">Prediction is route-constrained, not a road-directions API. When offline, the app keeps using the cached route and last synced group positions; it never labels a stale member position as live.</p></section>
 {error&&<div className="group-error">{error}</div>}</main></div>
}
