import React, { useEffect, useMemo, useState } from 'react';
import { Camera, Check, Clock3, RefreshCw, Upload, UserRoundSearch, X, MapPin, Activity } from 'lucide-react';
import AdminShell from '../components/AdminShell';
import StatusPill from '../components/StatusPill';
import { LOST_API, getJson, postJson } from '../api';

export default function LostFound(){
  const [health,setHealth]=useState(null),[cases,setCases]=useState([]),[cameras,setCameras]=useState([]),[alerts,setAlerts]=useState([]),[sightings,setSightings]=useState([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
  const load=async()=>{setHealth(await getJson(`${LOST_API}/health`));setCases(await getJson(`${LOST_API}/cases`,[]));setCameras(await getJson(`${LOST_API}/cameras`,[]));setAlerts(await getJson(`${LOST_API}/alerts?status=PENDING&limit=100`,[]));setSightings(await getJson(`${LOST_API}/sightings?limit=100`,[]));};
  useEffect(()=>{load();const id=setInterval(load,2500);return()=>clearInterval(id)},[]);
  const createCase=async(e)=>{e.preventDefault();setBusy(true);setMsg('');const fd=new FormData(e.currentTarget);try{const r=await fetch(`${LOST_API}/cases`,{method:'POST',body:fd});if(!r.ok)throw new Error(await r.text());setMsg('Missing-person case created. Camera workers refresh active cases automatically.');e.currentTarget.reset();await load();}catch(err){setMsg(`Could not create case: ${err.message}`)}finally{setBusy(false)}};
  const review=async(id,action)=>{try{await postJson(`${LOST_API}/alerts/${id}/${action}`);await load();}catch(e){setMsg(String(e))}};
  const totalFaces=cameras.reduce((n,c)=>n+(Number(c.faces)||0),0), totalMatched=cameras.reduce((n,c)=>n+(Number(c.matched_faces)||0),0);
  const byCase=useMemo(()=>{const m={}; sightings.forEach(s=>(m[s.case_id]??=[]).push(s));return m},[sightings]);
  return <AdminShell title="Lost & Found AI" subtitle="Single-photo face recognition · local InsightFace mode">
    <div className="module-toolbar"><div><h1><UserRoundSearch/> Lost Person Detection</h1><p>Reference enrollment → CCTV recognition → temporal confirmation → admin verification.</p></div><div className="toolbar-actions"><StatusPill ok={!!health} label={health?'BACKEND READY':'BACKEND OFFLINE'}/><button className="secondary-btn" onClick={load}><RefreshCw size={15}/>Refresh</button></div></div>
    <div className="overview-stats compact"><div><b>{cases.length}</b><span>Active Cases</span></div><div><b>{cameras.filter(c=>c.online).length}/{cameras.length}</b><span>Cameras Online</span></div><div><b>{totalFaces}</b><span>Faces Detected Now</span></div><div><b>{totalMatched}</b><span>Above Match Threshold</span></div><div><b>{alerts.length}</b><span>Pending Confirmations</span></div></div>
    <div className="two-col">
      <section className="panel"><div className="panel-title"><h2><Upload/> Register Missing Person</h2></div><form className="case-form" onSubmit={createCase}><label>Reference photo<input type="file" name="photo" accept="image/*" required/></label><div className="form-grid"><label>Name<input name="name" required placeholder="Person name"/></label><label>Age<input name="age" placeholder="Age"/></label><label>Last seen<input name="last_seen" placeholder="North Gate / Queue"/></label><label>Reporter contact<input name="reporter_contact" placeholder="Mobile number"/></label></div><button className="primary-btn" disabled={busy}>{busy?'Creating…':'Create Active Case'}</button>{msg&&<p className="form-message">{msg}</p>}</form></section>
      <section className="panel"><div className="panel-title"><h2><Activity/> Detection Meaning</h2></div><div className="explain-list"><div><b>Faces Detected</b><span>Every face currently seen by that camera.</span></div><div><b>Matched Faces</b><span>Faces currently above the configured similarity threshold. This is not yet a confirmed person.</span></div><div><b>Candidate Alert</b><span>A repeated, temporally confirmed match sent here for human approval.</span></div></div></section>
    </div>
    <section className="panel"><div className="panel-title"><h2><Camera/> Live Recognition Cameras</h2><span>{cameras.length} feeds</span></div><div className="camera-grid">{cameras.length?cameras.map(c=><div className="camera-card" key={c.camera_id}><div className="video-wrap"><img src={`${LOST_API}/cameras/${encodeURIComponent(c.camera_id)}/stream`} alt={c.camera_id}/><div className="video-overlay"><StatusPill ok={!!c.online}/><span>{c.camera_id}</span></div></div><div className="camera-meta"><div><b>{c.camera_location||c.camera_id}</b><span>{c.camera_id}</span></div><div className="mini-stats"><span><b>{Number(c.fps||0).toFixed(1)}</b> FPS</span><span><b>{c.faces||0}</b> Detected</span><span><b>{c.matched_faces||0}</b> Matched</span></div></div></div>):<Empty text="Start multi_camera.py after creating a case."/>}</div></section>
    <section className="panel"><div className="panel-title"><h2>Candidate Matches</h2><span>{alerts.length} pending</span></div><div className="alert-grid">{alerts.length?alerts.map(a=><article className="match-card" key={a.alert_id}><div className="compare"><figure><img src={`${LOST_API}/cases/${encodeURIComponent(a.case_id)}/reference`} alt="Reference"/><figcaption>Reference</figcaption></figure><div className="vs">VS</div><figure><img src={`${LOST_API}/alerts/${a.alert_id}/evidence`} alt="CCTV evidence"/><figcaption>CCTV Evidence</figcaption></figure></div><div className="match-info"><div><h3>{a.name}</h3><span className="similarity">{(Number(a.similarity)*100).toFixed(1)}% similarity</span></div><p><MapPin size={14}/>{a.camera_location} · {a.camera_id} · Track {a.track_id}</p><p><Clock3 size={14}/>{new Date(a.timestamp).toLocaleString()}</p></div><div className="match-actions"><button className="confirm" onClick={()=>review(a.alert_id,'confirm')}><Check size={16}/>Confirm Match</button><button className="reject" onClick={()=>review(a.alert_id,'reject')}><X size={16}/>Reject</button></div></article>):<Empty text="No candidate matches waiting for verification."/>}</div></section>
    <section className="panel"><div className="panel-title"><h2>Cross-Camera Sighting History</h2></div><div className="timeline-list">{Object.entries(byCase).slice(0,8).map(([caseId,rows])=><div className="timeline-case" key={caseId}><b>{rows[0]?.name||caseId}</b><div>{rows.slice(0,8).map((s,i)=><span key={s.sighting_id||i}>{s.camera_location}<small>{Number(s.similarity).toFixed(3)}</small></span>)}</div></div>)}{!sightings.length&&<Empty text="Sightings will appear after candidate alerts are created."/>}</div></section>
  </AdminShell>;
}
function Empty({text}){return <div className="empty-state">{text}</div>}
