#!/usr/bin/env python3
"""
One-time data prep. Run this once, commit the output, ship it with the app.

    pip install shapely pyproj requests
    python build_route_data.py --route route.geojson --out ../public/data

Produces:
    route.json   route polyline + total length + stage schedule
    pois.json    permanent facilities with chainage precomputed
    seed.sql     the same POIs as INSERT statements for Supabase

Overpass is called ONCE here. It is never called at runtime — it is rate
limited, often slow, and unavailable exactly when the network is worst.
"""

import argparse
import json
import sys
import time
from pathlib import Path

import requests
from pyproj import Geod
from shapely.geometry import LineString, Point, shape
from shapely.ops import nearest_points

GEOD = Geod(ellps="WGS84")
OVERPASS_URL = "https://overpass-api.de/api/interpreter"

# Corridor half-width for the OSM harvest, in metres.
CORRIDOR_M = 5000

# OSM tag -> our facility_kind
OSM_KINDS = {
    "hospital": "hospital",
    "clinic": "phc",
    "doctors": "phc",
    "pharmacy": "pharmacy",
}


def geodesic_length_km(coords):
    """True length of a lon/lat polyline, in km. Not planar."""
    total = 0.0
    for (lon1, lat1), (lon2, lat2) in zip(coords, coords[1:]):
        _, _, d = GEOD.inv(lon1, lat1, lon2, lat2)
        total += d
    return total / 1000.0


def chainage_km(line: LineString, coords, pt: Point, total_km: float):
    """
    Distance along the line to the nearest point, in km, plus the
    perpendicular offset in metres.

    shapely.project works in degrees, which are not equal-length. We use it
    only to find the fraction along the line, then scale by the true
    geodesic length. Good to a few metres over a 250 km route.
    """
    frac = line.project(pt, normalized=True)
    snap, _ = nearest_points(line, pt)
    _, _, offset_m = GEOD.inv(pt.x, pt.y, snap.x, snap.y)
    return round(frac * total_km, 3), round(offset_m, 1)


def build_overpass_query(coords, step=20):
    """
    Query around sampled waypoints rather than a giant polygon — Overpass
    handles many small around: clauses far better than one huge poly.
    """
    sampled = coords[::step] or coords
    parts = []
    for lon, lat in sampled:
        for tag in OSM_KINDS:
            parts.append(
                f'node(around:{CORRIDOR_M},{lat},{lon})["amenity"="{tag}"];'
            )
            parts.append(
                f'way(around:{CORRIDOR_M},{lat},{lon})["amenity"="{tag}"];'
            )
    return f"[out:json][timeout:180];({''.join(parts)});out center tags;"


def fetch_osm(coords, retries=3):
    query = build_overpass_query(coords)
    for attempt in range(retries):
        try:
            resp = requests.post(OVERPASS_URL, data={"data": query}, timeout=200)
            resp.raise_for_status()
            return resp.json().get("elements", [])
        except Exception as exc:
            wait = 15 * (attempt + 1)
            print(f"  overpass attempt {attempt + 1} failed ({exc}), "
                  f"retrying in {wait}s", file=sys.stderr)
            time.sleep(wait)
    raise RuntimeError("Overpass failed after retries. Try again later, or "
                       "use the Geofabrik Maharashtra extract offline.")


def normalise(elements, line, coords, total_km):
    seen, out = set(), []
    for el in elements:
        lat = el.get("lat") or (el.get("center") or {}).get("lat")
        lon = el.get("lon") or (el.get("center") or {}).get("lon")
        if lat is None or lon is None:
            continue

        osm_id = f"{el['type']}/{el['id']}"
        if osm_id in seen:
            continue
        seen.add(osm_id)

        tags = el.get("tags", {})
        kind = OSM_KINDS.get(tags.get("amenity"))
        if not kind:
            continue

        km, offset = chainage_km(line, coords, Point(lon, lat), total_km)
        if offset > CORRIDOR_M:
            continue

        out.append({
            "osmId": osm_id,
            "kind": kind,
            "name": tags.get("name") or tags.get("name:mr") or f"Unnamed {kind}",
            "lat": round(lat, 6),
            "lng": round(lon, 6),
            "chainageKm": km,
            "offsetM": offset,
            "status": "open",
            "contactPhone": tags.get("phone") or tags.get("contact:phone"),
            "source": "osm",
        })

    out.sort(key=lambda f: f["chainageKm"])
    return out


def to_seed_sql(pois, route_slug):
    lines = [
        "-- Generated by build_route_data.py. Safe to re-run.",
        "with r as (select id from routes where slug = "
        f"'{route_slug}')",
        "insert into facilities "
        "(route_id, kind, name, location, status, review, source, osm_id, contact_phone)",
        "values",
    ]
    rows = []
    for p in pois:
        name = p["name"].replace("'", "''")
        phone = f"'{p['contactPhone']}'" if p.get("contactPhone") else "null"
        rows.append(
            f"  ((select id from r), '{p['kind']}', '{name}', "
            f"ST_SetSRID(ST_MakePoint({p['lng']}, {p['lat']}), 4326)::geography, "
            f"'open', 'approved', 'osm', '{p['osmId']}', {phone})"
        )
    lines.append(",\n".join(rows))
    lines.append("on conflict (osm_id) do nothing;")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--route", required=True, help="GeoJSON LineString of the palkhi route")
    ap.add_argument("--stages", help="JSON array of mukkam stages")
    ap.add_argument("--out", default="./out")
    ap.add_argument("--slug", default="dnyaneshwar-2026")
    ap.add_argument("--skip-osm", action="store_true")
    args = ap.parse_args()

    raw = json.loads(Path(args.route).read_text())
    geom = raw["features"][0]["geometry"] if raw.get("type") == "FeatureCollection" else raw
    coords = list(shape(geom).coords)
    line = LineString(coords)
    total_km = geodesic_length_km(coords)

    print(f"route: {len(coords)} points, {total_km:.2f} km")
    spacing = total_km * 1000 / max(1, len(coords) - 1)
    print(f"average point spacing: {spacing:.0f} m")
    if spacing > 200:
        print("  WARNING: sparse polyline. Distances will read short. "
              "Trace at 50-100 m spacing.", file=sys.stderr)

    stages = json.loads(Path(args.stages).read_text()) if args.stages else []

    outdir = Path(args.out)
    outdir.mkdir(parents=True, exist_ok=True)

    (outdir / "route.json").write_text(json.dumps({
        "slug": args.slug,
        "coordinates": [[round(x, 6), round(y, 6)] for x, y in coords],
        "totalKm": round(total_km, 3),
        "startName": "Alandi",
        "endName": "Pandharpur",
        "destination": {"lat": coords[-1][1], "lng": coords[-1][0]},
        "stages": stages,
    }, separators=(",", ":")))

    if args.skip_osm:
        print("skipping OSM harvest")
        return

    print("querying overpass (this takes a minute)...")
    pois = normalise(fetch_osm(coords), line, coords, total_km)
    print(f"kept {len(pois)} facilities within {CORRIDOR_M} m of the route")

    for kind in set(p["kind"] for p in pois):
        print(f"  {kind}: {sum(1 for p in pois if p['kind'] == kind)}")

    (outdir / "pois.json").write_text(json.dumps(pois, separators=(",", ":")))
    (outdir / "seed.sql").write_text(to_seed_sql(pois, args.slug))

    size_kb = (outdir / "pois.json").stat().st_size / 1024
    print(f"\nbundle: pois.json {size_kb:.0f} KB")
    if size_kb > 500:
        print("  consider splitting by kind for lazy loading", file=sys.stderr)


if __name__ == "__main__":
    main()
